import { describe, expect, it, vi } from 'vitest';
// @ts-expect-error Static search helpers are intentionally Node.js ESM scripts.
import { canonicalizeZBSearchDatabase } from '../scripts/canonicalize-zbsearch.mjs';

describe('static search determinism', () => {
  it('finds a Chinese title when browser and build ICU dictionaries differ', async () => {
    let browserRuntime = false;
    const nativeSegmenter = new Intl.Segmenter(undefined, { granularity: 'word' });
    const runtimeIntl = Object.create(Intl);
    runtimeIntl.Segmenter = class {
      segment(input: string) {
        // Node and browser ICU versions can disagree on the same Chinese phrase.
        if (input === '考研核心题目') {
          return (browserRuntime ? ['考', '研', '核心', '题目'] : ['考研', '核心', '题目'])
            .map((segment) => ({ segment, isWordLike: true }));
        }
        return nativeSegmenter.segment(input);
      }
    };
    vi.stubGlobal('Intl', runtimeIntl);
    // @ts-expect-error Search exports are intentionally Node.js ESM scripts.
    const { exportSimpleIndex } = await import('../scripts/zbsearch-index.mjs');
    const raw = await exportSimpleIndex([
      { title: '考研核心题目', url: '/docs/math/core-questions', content: '考研核心题目' },
      { title: '二叉树的遍历', url: '/docs/408/trees', content: '遍历二叉树' },
      { title: '质心及形心', url: '/docs/math/centroid', content: '质心及形心' },
    ]);
    const database = JSON.parse(canonicalizeZBSearchDatabase(raw));
    vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify(database))));
    browserRuntime = true;
    const { createStaticSearchClient } = await import('../lib/static-search.mjs');
    const results = await createStaticSearchClient('/search/icu-regression.json', 10)
      .search('考研核心题目');
    expect(results.map((result) => result.url)).toEqual(['/docs/math/core-questions']);
  });

  it('removes autogenerated external document-id entropy without touching search data', () => {
    const shared = {
      type: 'simple',
      language: 'multilingual',
      index: { searchableProperties: ['title', 'content'] },
      docs: { docs: { 1: { title: 'A', url: '/docs/a' }, 2: { title: 'B', url: '/docs/b' } } },
      sorting: { enabled: true },
      pinning: {},
    };

    const first = JSON.stringify({
      ...shared,
      internalDocumentIDStore: {
        internalIdToId: ['25775151-0', '25775151-1'],
      },
    });
    const second = JSON.stringify({
      ...shared,
      internalDocumentIDStore: {
        internalIdToId: ['25799174-0', '25799174-1'],
      },
    });

    const canonicalFirst = canonicalizeZBSearchDatabase(first);
    const canonicalSecond = canonicalizeZBSearchDatabase(second);

    expect(canonicalFirst).toBe(canonicalSecond);
    const parsed = JSON.parse(canonicalFirst);
    expect(parsed.internalDocumentIDStore.internalIdToId).toEqual([
      'static-search-1',
      'static-search-2',
    ]);
    expect(parsed.docs).toEqual(shared.docs);
    expect(parsed.index).toEqual(shared.index);
  });
});
